"use strict";
const fs = require("node:fs");
const path = require("node:path");

function generateMermaidPipeline(data) {
  const modules = data.decomposed.modules || [];
  const clean = modules.filter(m => m.clean).length;
  const failed = modules.length - clean;

  return `\`\`\`mermaid
flowchart TD
    A["📄 ${path.basename(data.original.file)}<br/>${data.original.lines.toLocaleString()} lines | ${data.original.functions} functions"] --> B["🔍 ANALYZE<br/>Health: ${(data.health?.overall || 0).toFixed(1)}"]
    B --> C["📸 CHARACTERIZE<br/>${data.characterize?.exportCount || 0} exports snapshotted"]
    C --> D["📐 PLAN<br/>${modules.length} modules via ${data.plan?.provider || 'LLM'}"]
    D --> E["⚙️ EXTRACT<br/>${modules.length} modules generated"]
    E --> F["🔧 FIX-IMPORTS<br/>Mechanical path rewrite"]
    F --> G["✅ VERIFY<br/>${clean}/${modules.length} clean"]
    G --> H["📊 SCORE: ${data.refactoryScore}"]

    style A fill:#e74c3c,color:#fff
    style H fill:#${data.refactoryScore >= 0.9 ? '2ecc71' : data.refactoryScore >= 0.7 ? 'f39c12' : 'e74c3c'},color:#fff
\`\`\``;
}

function generateMermaidModuleGraph(data) {
  const modules = data.decomposed.modules || [];
  if (modules.length === 0) return "";

  let graph = "```mermaid\nflowchart LR\n";
  graph += `    ORIG["${path.basename(data.original.file)}<br/>${data.original.lines}L"] --> INDEX["index.js<br/>re-export"]\n`;
  for (const m of modules) {
    const status = m.clean ? "✅" : "❌";
    const color = m.clean ? "#2ecc71" : "#e74c3c";
    const id = m.file.replace(/[^a-zA-Z0-9]/g, "_");
    graph += `    INDEX --> ${id}["${status} ${m.file}<br/>${m.lines}L"]\n`;
    graph += `    style ${id} fill:${color},color:#fff\n`;
  }
  graph += "```";
  return graph;
}

function generateMarkdown(data, pipelineDiagram, moduleDiagram) {
  return `# Refactory Decomposition Report

**Generated:** ${data.timestamp}
**Refactory Score:** ${data.refactoryScore} / 1.00

## Pipeline

${pipelineDiagram}

## Original
- **File:** ${data.original.file}
- **Lines:** ${data.original.lines.toLocaleString()}
- **Functions:** ${data.original.functions}

## Decomposed
- **Modules:** ${data.decomposed.moduleCount}
- **Total lines:** ${data.decomposed.totalLines.toLocaleString()}
- **Max module:** ${data.decomposed.maxModuleLines} lines
- **Avg module:** ${data.decomposed.avgModuleLines} lines
- **Clean rate:** ${data.decomposed.cleanRate}%

## Module Graph

${moduleDiagram}

## Module Details

| Module | Lines | Status |
|--------|-------|--------|
${data.decomposed.modules.map((m) => `| ${m.file} | ${m.lines} | ${m.clean ? "✅ OK" : "❌ FAIL"} |`).join("\n")}

---
*Generated by [Refactory](https://refactory.codedrop.codes)*
`;
}

function generateMermaidPipelineRaw(data) {
  const modules = data.decomposed.modules || [];
  const clean = modules.filter(m => m.clean).length;
  return `flowchart TD
    A["${path.basename(data.original.file)}\\n${data.original.lines.toLocaleString()} lines | ${data.original.functions} functions"] --> B["ANALYZE\\nHealth: ${(data.health?.overall || 0).toFixed(1)}"]
    B --> C["CHARACTERIZE\\n${data.characterize?.exportCount || 0} exports snapshotted"]
    C --> D["PLAN\\n${modules.length} modules via ${data.plan?.provider || 'LLM'}"]
    D --> E["EXTRACT\\n${modules.length} modules generated"]
    E --> F["FIX-IMPORTS\\nMechanical path rewrite"]
    F --> G["VERIFY\\n${clean}/${modules.length} clean"]
    G --> H["SCORE: ${data.refactoryScore}"]
    style A fill:#e74c3c,color:#fff
    style H fill:#${data.refactoryScore >= 0.9 ? '2ecc71' : data.refactoryScore >= 0.7 ? 'f39c12' : 'e74c3c'},color:#fff`;
}

function generateMermaidModuleGraphRaw(data) {
  const modules = data.decomposed.modules || [];
  if (modules.length === 0) return "";
  let graph = `flowchart LR\n    ORIG["${path.basename(data.original.file)}\\n${data.original.lines}L"] --> INDEX["index.js\\nre-export"]\n`;
  for (const m of modules) {
    const color = m.clean ? "#2ecc71" : "#e74c3c";
    const id = m.file.replace(/[^a-zA-Z0-9]/g, "_");
    graph += `    INDEX --> ${id}["${m.clean ? "OK" : "FAIL"} ${m.file}\\n${m.lines}L"]\n`;
    graph += `    style ${id} fill:${color},color:#fff\n`;
  }
  return graph;
}

function generateHtml(data) {
  const basename = path.basename(data.original.file);
  const scoreColor = data.refactoryScore >= 0.9 ? "#3fb950" : data.refactoryScore >= 0.7 ? "#d29922" : "#f85149";
  const cleanCount = data.decomposed.modules.filter(m => m.clean).length;
  const totalCount = data.decomposed.modules.length;
  const pipelineMermaid = generateMermaidPipelineRaw(data);
  const moduleMermaid = generateMermaidModuleGraphRaw(data);

  const moduleRows = data.decomposed.modules.map(m => {
    const status = m.clean ? '<span class="ok">OK</span>' : '<span class="err">FAIL</span>';
    const bar = Math.min(100, Math.round((m.lines / data.original.lines) * 100));
    return `<tr>
      <td class="mono">${m.file}</td>
      <td class="num">${m.lines.toLocaleString()}</td>
      <td>${status}</td>
      <td><div class="bar"><div class="bar-fill" style="width:${bar}%"></div></div></td>
    </tr>`;
  }).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Refactory Report — ${basename}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&display=swap');
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  :root {
    --bg: #0d1117; --bg-card: #161b22; --border: #30363d;
    --text: #e6edf3; --text-dim: #8b949e;
    --green: #3fb950; --green-dim: #238636; --blue: #58a6ff;
    --purple: #bc8cff; --orange: #d29922; --red: #f85149;
    --mono: 'JetBrains Mono', 'Fira Code', monospace;
  }
  body { background: var(--bg); color: var(--text); font-family: var(--mono); font-size: 14px; line-height: 1.6; padding: 32px; max-width: 1100px; margin: 0 auto; }
  a { color: var(--blue); text-decoration: none; }
  h1 { font-size: 1.5rem; margin-bottom: 4px; }
  h1 span { color: var(--green); }
  h2 { font-size: 1.1rem; margin: 40px 0 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; }
  .meta { color: var(--text-dim); font-size: 0.8rem; margin-bottom: 24px; }

  /* Score hero */
  .score-hero { display: flex; align-items: center; gap: 24px; background: var(--bg-card); border: 1px solid var(--border); border-radius: 8px; padding: 24px; margin: 24px 0; }
  .score-num { font-size: 3rem; font-weight: 700; }
  .score-detail { flex: 1; }
  .score-detail p { color: var(--text-dim); font-size: 0.85rem; margin-bottom: 4px; }

  /* Stats row */
  .stats { display: flex; gap: 24px; flex-wrap: wrap; margin: 24px 0; }
  .stat { background: var(--bg-card); border: 1px solid var(--border); border-radius: 8px; padding: 16px 20px; flex: 1; min-width: 140px; }
  .stat .num { font-size: 1.3rem; font-weight: 700; color: var(--green); }
  .stat .label { font-size: 0.72rem; color: var(--text-dim); margin-top: 2px; }

  /* Mermaid */
  .mermaid-container { background: var(--bg-card); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin: 16px 0; overflow-x: auto; }
  .mermaid { text-align: center; }

  /* Table */
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th { text-align: left; color: var(--text-dim); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; padding: 8px 12px; border-bottom: 1px solid var(--border); }
  td { padding: 8px 12px; border-bottom: 1px solid var(--border); font-size: 0.82rem; }
  tr:hover { background: rgba(88, 166, 255, 0.04); }
  .mono { font-family: var(--mono); color: var(--blue); }
  .num { text-align: right; }
  .ok { color: var(--green); font-weight: 700; }
  .err { color: var(--red); font-weight: 700; }

  /* Size bars */
  .bar { width: 100%; height: 6px; background: var(--bg); border-radius: 3px; overflow: hidden; min-width: 80px; }
  .bar-fill { height: 100%; background: var(--green); border-radius: 3px; transition: width 0.3s; }

  /* Footer */
  footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid var(--border); color: var(--text-dim); font-size: 0.72rem; text-align: center; }

  @media (max-width: 640px) {
    body { padding: 16px; }
    .score-hero { flex-direction: column; text-align: center; }
    .stats { flex-direction: column; }
  }
</style>
</head>
<body>

<h1>Refactory Report — <span>${basename}</span></h1>
<p class="meta">Generated ${data.timestamp} &middot; <a href="https://refactory.codedrop.codes">refactory.codedrop.codes</a></p>

<div class="score-hero">
  <div class="score-num" style="color: ${scoreColor}">${data.refactoryScore}</div>
  <div class="score-detail">
    <p><strong>Refactory Score</strong> &mdash; clean_rate &times; size_reduction</p>
    <p>${cleanCount}/${totalCount} modules clean &middot; largest module ${data.decomposed.maxModuleLines}L vs original ${data.original.lines.toLocaleString()}L</p>
  </div>
</div>

<div class="stats">
  <div class="stat"><div class="num">${data.original.lines.toLocaleString()}</div><div class="label">original lines</div></div>
  <div class="stat"><div class="num">${totalCount}</div><div class="label">modules</div></div>
  <div class="stat"><div class="num">${data.decomposed.cleanRate}%</div><div class="label">clean rate</div></div>
  <div class="stat"><div class="num">${data.decomposed.avgModuleLines}</div><div class="label">avg module lines</div></div>
  <div class="stat"><div class="num">${data.decomposed.maxModuleLines}</div><div class="label">max module lines</div></div>
</div>

<h2>Pipeline</h2>
<div class="mermaid-container">
  <pre class="mermaid">
${pipelineMermaid}
  </pre>
</div>

<h2>Module Graph</h2>
<div class="mermaid-container">
  <pre class="mermaid">
${moduleMermaid}
  </pre>
</div>

<h2>Module Details</h2>
<table>
  <thead><tr><th>Module</th><th class="num">Lines</th><th>Status</th><th>Size vs Original</th></tr></thead>
  <tbody>
${moduleRows}
  </tbody>
</table>

<footer>
  Generated by <a href="https://refactory.codedrop.codes">Refactory</a> &middot; AGPL-3.0
</footer>

<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
  mermaid.initialize({
    startOnLoad: true,
    theme: 'dark',
    themeVariables: {
      darkMode: true,
      background: '#0d1117',
      primaryColor: '#238636',
      primaryTextColor: '#e6edf3',
      primaryBorderColor: '#30363d',
      lineColor: '#8b949e',
      secondaryColor: '#161b22',
      tertiaryColor: '#21262d'
    }
  });
</script>

</body>
</html>`;
}

async function report(args) {
  const metricsPath = path.resolve(args.metricsFile);
  const data = JSON.parse(fs.readFileSync(metricsPath, "utf8"));
  const format = args.format || "markdown";

  const pipelineDiagram = generateMermaidPipeline(data);
  const moduleDiagram = generateMermaidModuleGraph(data);

  if (format === "html") {
    const html = generateHtml(data);
    const outputPath = args.outputPath
      ? path.resolve(args.outputPath).replace(/\.md$/, ".html")
      : null;
    if (outputPath) {
      fs.writeFileSync(outputPath, html, "utf8");
    }
    return { format: "html", content: html, outputPath };
  }

  const md = generateMarkdown(data, pipelineDiagram, moduleDiagram);

  if (args.outputPath) {
    fs.writeFileSync(path.resolve(args.outputPath), md, "utf8");
  }

  return { format, content: md, outputPath: args.outputPath || null };
}

module.exports = { report, generateMermaidPipeline, generateMermaidModuleGraph };
